# Generated by Django 5.0.3 on 2024-03-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
